import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Prezentare from "../components/Prezentare";
import Cadastru from "../components/Cadastru";
import Topografie from "../components/Topografie";
import Certificat from "../components/Certificat";
import Preturi from "../components/Preturi";
import NavMenu from "../components/NavMenu";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div
      className={styles.mainContainer + " container-fluid m-0 p-0"}
      style={{ height: "fit-content", minHeight: "100vh" }}
    >
      <Head>
        <title>Cadastru Constanta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/titleIcon1.png" />
      </Head>

      <div className={styles.title + " row m-0 p-0"}>
        <h4 className={styles.firstTitle}>Cadastru</h4>
        <h4 className={styles.secondTitle}>Constanta</h4>
      </div>

      <div
        className={
          styles.contentContainer +
          " m-0 p-0 d-flex flex-column flex-lg-row col-12"
        }
        
      >
        <NavMenu />
        <div
          className={
            styles.sections +
            " row m-0 p-0 mt-3 col-auto col-lg-6 px-3 mx-lg-auto order-3 order-lg-2"
          }
        >
          <Prezentare />
          <Cadastru />
          <Topografie />
          <Certificat />
          <Preturi />
        </div>
        <Contact />
      </div>
    </div>
  );
}
